### PR TITLE
Implement self.prefetch for zabbix_proxy

### PR DESCRIPTION
**Pull request by baurmatt**
#### Pull Request (PR) description
The template parameter got removed because it had no function and just added additional API calls. I therefore labeled this PR `backwards-incompatible`.

#### This Pull Request (PR) fixes the following issues
This is another change for #570.

### CODE REVIEW

**Comment by baurmatt** [comment]
The tests which failed did this because of:

```
The job exceeded the maximum log length, and has been terminated.
```

Pretty sure that this isn't a problem of this change ;)

**Comment by alexjfisher** [comment]
@baurmatt And not because https://github.com/voxpupuli/puppet-zabbix/pull/642/files#diff-677c6e628f74bf4e5fe32149fb37a725R29 printed a crazy amount of stuff to stdout?

**Comment by baurmatt** [comment]
@alexjfisher LOL (literally) :D Good catch, thanks! :) I've updated the code. But there still two failing tests. As those are also failing in the master, I guess I'm good here.

**Comment by baurmatt** [comment]
Tests will be fixed with #646.

**Pull request merged**
