### PR TITLE
Add missing enable => true for zabbix-java-gateway

### PR DESCRIPTION
**Pull request by stefanandres**
The zabbix-java-gateways service should be enabled

### CODE REVIEW

**Comment by bastelfreak** [comment]
thansk for the fix @stefanandres. Can you take a look at the failing travis jobs?

**Comment by stefanandres** [comment]
Of course, it seems I've added and extra `end` - tests should run with success now.

**Comment by stefanandres** [comment]
Oh, this is the same Bug I fixed a few months ago:

https://github.com/voxpupuli/puppet-zabbix/pull/516/files#diff-937db54f48c43542eecbbe379d023313R94 prevents this PR to work. I'll rewrite this bit today/tomorrow like I did in proxy.pp

**Comment by stefanandres** [comment]
Somehow the redhat/centos-5 line troubles the CI, can we remove support this kind of old OS? 

```
  # Workaround for: The redhat provider can not handle attribute enable
  # This is only happening when using an redhat family version 5.x.
  if $::osfamily == 'redhat' and $::operatingsystemrelease =~ /^5.*/ {
    $enable = undef
  }  else {
    $enable = true
  }
```

**Comment by bastelfreak** [comment]
@stefanandres that is indeed legacy. We don't support centos 5 anymore. You can purge the block if you want.

**Comment by stefanandres** [comment]
Hm, do you understand the current travis error?
https://travis-ci.org/voxpupuli/puppet-zabbix/jobs/405240150 => 
```-07-18T07:54:05.627727 #5234]  INFO -- : Creating symlink from spec/fixtures/modules/zabbix to /home/travis/build/voxpupuli/puppet-zabbix
12 processes for 16 specs, ~ 1 specs per process
/home/travis/.rvm/gems/ruby-2.1.9/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.16.3/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.1.9/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:24:in `<main>'
/home/travis/.rvm/gems/ruby-2.1.9/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.16.3/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.1.9/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:24:in `<main>'
/home/travis/.rvm/gems/ruby-2.1.9/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.16.3/exe/bundle (LoadError)
```

It's not like I touched any of this stuff. :-)

**Comment by bastelfreak** [comment]
@stefanandres there is currently an issue with one of our dependencies. Please rebase after https://github.com/voxpupuli/puppet-zabbix/pull/518 got merged.

**Comment by stefanandres** [comment]
I've rebased against the current master and now the checks are all successfull

**Comment by bastelfreak** [comment]
Thanks @stefanandres !

**Pull request merged**
