### PR TITLE
Bump zabbixapi version

### LINKED ISSUE #544: API Error
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.3
- Ruby: ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
- Distribution: CentOS Linux release 7.5.1804 
- Module version: 6.4.2

setting up zabbix server with a super minimal class right now.. 
class { 'zabbix':
    zabbix_url         => 'test0.local',
    manage_resources   => $manage_resources,
  }
}

This is totally failing to manage the resources.

Error: Could not set 'present' on ensure: Server answer API error
 {
  "code": -32602,
  "message": "Invalid params.",
  "data": "Incorrect arguments passed to function."
}
 on request:
 {
  "method": "host.update",
  "params": [
    {
      "host": "test1.local",
      "interfaces": [
        {
          "type": 1,
          "main": 1,
          "ip": null,
          "dns": "test1.local",
          "port": "10050",
          "useip": 1
        }
      ],
      "templates": [
        10001,
        10102
      ],
      "groups": [
        {
          "groupid": 15
        }
      ],
      "hostid": 10254
    }
  ],
  "id": 37574,
  "jsonrpc": "2.0",
  "auth": "cec4529954ff855133c82ac6fb43e0f0"
}

I would like to think I am doing something wrong.. But even the zabbixapi gem is having problems, as I end up needing to "fix" the gem to get this far..   As it was doing this.. 

Error: /Stage[main]/Zabbix::Resources::Web/Zabbix_host[test1.local]: Could not evaluate: Zabbix API version: 3.4.14 is not support by this version of zabbixapi

Should I be forcing to older versions to get this to work?

### LINKED ISSUE #621: Zabbix 4.2 Support
Any chance to have zabbix 4.2 support?

### LINKED ISSUE #689: Add Support for Zabbix 5.0
The current version of this module does not support Zabbix 5.0. I know this Zabbix version just got released a couple of days ago, but it would be awesome if/when it is supported. I understand this would take time.
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Latest
- Ruby: Latest with Puppet
- Distribution: CentOS 7
- Module version: Latest

## How to reproduce (e.g Puppet code you use)
Use the current version of these Puppet library to deploy a Zabbix 5.0 server.
## What are you seeing
Some of the packages have been renamed, so it fails to install the old names. In the end, the web based UI for Zabbix is broken.

## What behaviour did you expect instead
I would guess I was to optimistic, I expected to have a working Zabbix server.

### PR DESCRIPTION
**Pull request by fraenki**
#### Pull Request (PR) description
This is a re-submission of #623, because the original PR was probably abandoned.

* Re-submission of #623 (with latest version of zabbixapi)
* Rebased against latest master branch
* Bumps acceptance tests to Zabbix LTS release 4.4 (it's too early for 5.x)

#### This Pull Request (PR) fixes the following issues
Fixes #621 (Zabbix 4.2 support)
Fixes #544 (Zabbix 3.4 support)
Fixes #689 (Zabbix 5.0 support; partially, should be considered the first step)

### CODE REVIEW

**Comment by fraenki** [comment]
@kenyon I've fixed the [failing acceptance tests](https://travis-ci.org/github/voxpupuli/puppet-zabbix/builds/754899759). Please merge :)

FWIW, Travis CI still [reports a failure](https://travis-ci.org/github/voxpupuli/puppet-zabbix/jobs/754899766), but it's unrelated to my changes:

```
"error":"toomanyrequests: You have reached your pull rate limit. 
You may increase the limit by authenticating and upgrading: 
https://www.docker.com/increase-rate-limit"
```

**Comment by kenyon** [comment]
I reran the failed test, and it passed.

**Review by kenyon — APPROVED** [review]

**Comment by bastelfreak** [comment]
thanks for the PR! I will do some updates to the others we've open and try to merge this one later today

**Comment by bastelfreak** [comment]
Related PRs:
* https://github.com/voxpupuli/puppet-zabbix/pull/733
* https://github.com/voxpupuli/puppet-zabbix/pull/728

**Comment by fraenki** [comment]
@bastelfreak Thank you! I think it's safe to close #623 too (it is the abandoned PR).

**Pull request merged**
