### PR TITLE
Add repo for Ubuntu Focal on arm64

### PR DESCRIPTION
**Pull request by emetriqChris**
Zabbix now provides Ubuntu Focal deb packages for the arm64 architecture:
https://support.zabbix.com/browse/ZBXNEXT-5982

They can be found under a different URL than "usual":
https://repo.zabbix.com/zabbix/5.2/ubuntu-arm64/

so the repo.pp manifest has to be adapted to refelct this.

Be careful: Right now, Zabbix only provides packages for version 5.0 and 5.2.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@emetriqChris can you please rebase this against our latest master branch and add tests for it?

**Comment by emetriqChris** [comment]
Hi,

sorry for the very, very big delay. I did a rebase.

But I'm a little bit lost when it comes to adding checks. My change only has an impact on Ubuntu 20.04 aarch64 - so the checks should run with this architecture. Sadly GitHub Actions aren't avaible on arm64 (https://github.com/actions/virtual-environments/issues/2552) - so running against aarch64 is not possible :-(

Greetings from Hamburg
Chris

**Comment by root-expert** [comment]
Hey @emetriqChris , there's no need to add acceptance tests for this. Just some basic unit tests for the repo class. Take a look [here](https://github.com/voxpupuli/puppet-zabbix/blob/master/spec/classes/repo_spec.rb)

**Comment by emetriqChris** [comment]
Moin,

I think I broke something one my side, for example I added some unit tests which do not show up in this pull request.

Is it okay if I close/delete this PR and start over with a fresh fork and PR?

Greetings from Hamburg
Chris

**Comment by bastelfreak** [comment]
of course you can close the PR and raise a new one. if you've questions you can also always ping me in the puppet-community slack or #voxpupuli on libera IRC,

greetings from cologne :)

**Pull request closed without merging**
