### PR TITLE
Drop Puppet 5 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by kenyon** [comment]
The error is here: https://github.com/voxpupuli/puppet-zabbix/pull/742/checks?check_run_id=1999631797#step:5:8194

This is the first result in Google: https://tickets.puppetlabs.com/browse/MODULES-3466

:thinking:

**Comment by root-expert** [comment]
Maybe exporting language variables like so:

```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

when docker container starts could help?

**Comment by bastelfreak** [comment]
whyyyyyyyyyy is that error coming up again :(. @trevor-vaughan any idea how we can fix that? should beaker-docker set those env vars or modify the puppetlabs-postgresql module or something else?

**Comment by bastelfreak** [comment]
this also includes https://github.com/voxpupuli/puppet-zabbix/pull/744

**Comment by bastelfreak** [comment]
This PR now includes https://github.com/voxpupuli/puppet-zabbix/pull/746 and https://github.com/voxpupuli/puppet-zabbix/pull/744

**Review by kenyon — APPROVED** [review]

**Pull request merged**
