### PR TITLE
Allow to configure access to server from more than one web front-end

### PR DESCRIPTION
**Pull request by flaupretre**
Currently, only one host|address can be sent as $zabbix_web or $zabbix_web_ip to zabbix::database. So, only one web front-end can be authorized. If you have several web font-ends to your zabbix server, authorizing these hosts cannot be automated.

This PR allows the two parameters to be provided as arrays of hostnames | IP addresses.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @flaupretre, thanks for the PR. Can you please rebase against latest master of our repo to fix the conflicts?

**Comment by flaupretre** [comment]
Rebased to master. Please double check the logic because of the new 'database_host_ip' parameter.

**Comment by bastelfreak** [comment]
please check the travis log, there is still some trailing whitespace which blocks the unit tests. Are you able to add some rspec tests to verify your implemented logic?

**Comment by flaupretre** [comment]
I think trailing whitespaces are fixed now.

Sorry, but I don't know how to write rspec tests. I will have a look when I have time but, from the outside, it seems quite complex (as everything I am discovering from the Ruby world).

**Comment by bastelfreak** [comment]
Hi. I'm going to close this PR due to inactivity. Please reopen it if you want to continue working on it. If you've any questions you can reach out to us in #voxpupuli on freenode and https://slack.puppet.com.

**Pull request closed without merging**
