### PR TITLE
Add Zabbix 4.0 compatibility

### PR DESCRIPTION
**Pull request by Lord-Y**
Small updates to add Zabbix 4.0 compatibility

### CODE REVIEW

**Comment by Lord-Y** [comment]
@bastelfreak @dj-wasabi  Any idea on the CI issue? The error is not explicit at all.

**Comment by alexjfisher** [comment]
Looks like the travis job had hung.  I restarted it and all looks good now.

**Comment by alexjfisher** [comment]
Looks like the travis job had hung.  I restarted it and all looks good now.

**Comment by alexjfisher** [comment]
The `config_mode` parameter change looks unrelated to Zabbix 4.  Could it be put into a separate PR please?

**Comment by Lord-Y** [comment]
@alexjfisher Yeah not related but when I try to do my PR, I got a conflict because of that so I have to solve it by merging with the new values.

**Comment by alexjfisher** [comment]
It's best practice to use topic branches instead of making changes in your fork's master branch.

Basically, your master branch should only ever contain changes that also exist in the upstream/master.
Periodically, you'd then sync upstream/master back into your fork. https://help.github.com/articles/syncing-a-fork/

If you are stuck with git issues, there are plenty of people who can help you out on both the IRC #voxpupuli channel or in the Puppet Community #voxpupuli slack channel.

**Comment by bastelfreak** [comment]
Thanks @Lord-Y. Can you take a look at the used email address in your commits? It isn't associated with your github account.

**Comment by Lord-Y** [comment]
@bastelfreak Sorry, I'll make sure to better use git next time I'll commit, email, fork, rebase and else

**Comment by bastelfreak** [comment]
Hey, that's totally fine, nothing to worry about. You can always ping us in our IRC channel #voxpupuli on freenode or at https://puppetcommunity.slack.com if you've questions. It should be enough to add `yohann@lord-y.com` to your github profile. The address seems to be missing.

**Pull request merged**
