### PR TITLE
Adapt to zabbix-3.2 and higher.

### PR DESCRIPTION
**Pull request by yevtushenko**
A few changes to adapt module to zabbix-3.2 and higher versions.

Some of ```3.0``` strings replaced with regular expressions, some ```@zabbix_version == '3.0'``` replaced with ```@zabbix_version >= '3.0'```.

### CODE REVIEW

**Comment by bastelfreak** [comment]
HI @yevtushenko , thanks for the PR. Can you please take a look at the failed spec tests and also add a few new ones that test several zabbix versions?

**Comment by yevtushenko** [comment]
@bastelfreak I'll do it soon.

**Comment by yevtushenko** [comment]
@bastelfreak  It very strange that test fails. I've run test on my machine and it passed successfully.

**Comment by bastelfreak** [comment]
Seems to be fine now, thanks @yevtushenko!

**Comment by yevtushenko** [comment]
@bastelfreak I've removed the mysql tests for zabbix-3.2 which I added before because it fails on these new tests. I think these tests should be there, so I can try to create separate PR for them.

**Comment by bastelfreak** [comment]
Yes, please create a seperate PR.

**Comment by yevtushenko** [comment]
@bastelfreak Also current PR covers #286 and #287 (including tests you requested).

**Pull request merged**
