### PR TITLE
Added details to host network interface to configure SNMP hosts

### PR DESCRIPTION
**Pull request by oraziobattaglia**
#### Pull Request (PR) description

Following the pull request #697 we add an hash of interface options to configure some details about SNMP.
We want to use to add SNMP host with community and other details.

Example

```
  zabbix_host { 'SNMPServer':
    ipaddress     => '192.168.1.1',
    use_ip        => true,
    port          => 161,
    groups        => ['SNMP servers'],
    group_create  => true,
    templates     => ['Template Module ICMP Ping'],
    macros        => [],
    proxy         => '',
    interfacetype => 2,
    interfacedetails => {"version" => 2, "bulk" => 0, "community" => "public"},
  }
```

Using interfacetype = 2 without details we have the error

```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params.","data":"Incorrect arguments passed to function."},"id":42907}
```

#### This Pull Request (PR) fixes the following issues

No issues opened, follow pull request #697

### CODE REVIEW

**Comment by oraziobattaglia** [comment]
@smortex thanks for the detailed istructions about the rebase, was a hard work for me :-)! I'm not expert of rebase! Hope now is ok.

**Comment by root-expert** [comment]
Good job!
The only thing is that you have two commits now. You can squash the last one by doing:

```
git rebase -i HEAD~2
```

You should see two commits:
* Added details to host network interface for SNMP
* Merge branch 'master' into master

On the second one type fixup instead of pick, save and quit your editor. You should end up with just one commit. Then force push it.

```
git push -f
```

Thanks again!

**Comment by oraziobattaglia** [comment]
@root-expert thank you for the suggestion but when I do
git rebase -i HEAD~2
I see a lot of commit not mine and only the commit "Added details to host network interface for SNMP". I don't see the commit "Merge branch 'master' into master".
I don't know how to procede to squash the 2 commits. The second one "Merge branch 'master' into master" was made by a file conflict resolution made here by GUI.
Thank you

**Comment by root-expert** [comment]
Hey @oraziobattaglia are you able to join on [Libera.chat](https://web.libera.chat/) irc on channel #voxpupuli to help you further?
Thank you!

**Review by bastelfreak — APPROVED** [review]

**Comment by oraziobattaglia** [comment]
@root-expert @bastelfreak @smortex thank you for the support and the merge!

**Pull request merged**
