### PR TITLE
Allow puppetlabs/apache 5.x, puppetlabs/concat 6.x, puppetlabs/firewall 2.x, puppetlabs/mysql 9.x, puppetlabs/stdlib 6.x; drop puppetlabs/ruby dependency

### PR DESCRIPTION
**Pull request by dhoppe**
This depends on #605.

### CODE REVIEW

**Comment by bastelfreak** [comment]
I will rebase this branch.

**Comment by dhoppe** [comment]
@bastelfreak I see. You are also not a friend of alphabetically sorted modules. :(

**Comment by bastelfreak** [comment]
I'm a friend of a small diff :D

**Comment by bastelfreak** [comment]
Why is postgresql 6 pulling in stdlib 5 during the tests :thinking:

**Comment by bastelfreak** [comment]
wahhhh postgresql pulls in concat 5 which pulls in stdlib 5 ....

**Comment by bastelfreak** [comment]
this PR depends on https://github.com/puppetlabs/puppetlabs-postgresql/pull/1082. Pinged on slack

**Comment by dhoppe** [comment]
> Why is postgresql 6 pulling in stdlib 5 during the tests thinking

The dependencies of puppetlabs/concat are broken. 
* https://github.com/puppetlabs/puppetlabs-concat/blob/5.3.0/metadata.json

**Comment by dhoppe** [comment]
@bastelfreak There is an issue with puppetlabs/ruby: 
* https://github.com/puppetlabs/puppetlabs-ruby/blob/master/metadata.json#L72-L79

I need to take a closer look to decide if we really need this module. :(

**Comment by bastelfreak** [comment]
marked as bug because of https://github.com/voxpupuli/puppet-openvpn/pull/340

**Comment by bastelfreak** [comment]
In my opinion we should label this `backwards-incompatible` because stuff that the puppetlabs/ruby dependency did now needs to be handled in a profile (in case anybody needs it, it's optional).

**Pull request merged**
