### PR TITLE
Fix managing proxy servers

### PR DESCRIPTION
**Pull request by breaker1**
This is a fix for #334 

I found a couple issues with the `zabbix_proxy` ruby code used for managing the proxy resources on the zabbix server. I __think__ this is fixed in a proper way. I am not a Ruby developer, but it has fixed the issues I was experiencing with my manifests.

### CODE REVIEW

**Comment by breaker1** [comment]
I don't understand why the unit test is failing... Can anyone help shed some light on this?

**Comment by bastelfreak** [comment]
Hi @breaker1, thanks for this PR. Those issues got fixed in master, could you please rebase against our latest master?

**Comment by ekohl** [comment]
@breaker1 it looks like you merged in master rather than rebase. Usually it's ```git rebase master``` and then you do need to force push but it'll result in a cleaner history and easier for us to review.

**Comment by breaker1** [comment]
@ekohl My apologies. I will try to do it correctly with my next pull request.

**Comment by ekohl** [comment]
@breaker1 no worries, it happens and it's easy to fix.

**Comment by breaker1** [comment]
@ekohl Is that something I need to do? If so, how?

**Comment by breaker1** [comment]
@ekohl @bastelfreak 

Going to close this request and create a new one which is done correctly.

**Pull request closed without merging**
