### PR TITLE
Fix #594

### LINKED ISSUE #594: check_template_in_host function missing parameter
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.10
- Ruby: 2.3

## How to reproduce (e.g Puppet code you use)

Make use of the Zabbix_userparameters resource. For example:

```
zabbix::userparameters { 'nginx':
      content   => "UserParameter=nginx.json[*],curl -s 'http://$1:$2/_status' | tr -d a-zA-Z\\n | tr ' :' ',' | sed -e s/',,*'/,/g -e s/'^,'/'{\"nginx\":['/g -e s/',$'/']}'/g",
      template => 'Template App Nginx',
    }
```

## What are you seeing

`Error: /Stage[main]/Zabbix::Resources::Web/Zabbix_userparameters[my.hostname_testing_nginx]: Could not evaluate: wrong number of arguments (given 2, expected 1)`

## What behaviour did you expect instead

It should work.

## Output log

`Error: /Stage[main]/Zabbix::Resources::Web/Zabbix_userparameters[my.hostname_testing_nginx]: Could not evaluate: wrong number of arguments (given 2, expected 1)
/opt/puppetlabs/puppet/cache/lib/puppet/provider/zabbix.rb:93:in `check_template_in_host'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/zabbix_userparameters/ruby.rb:25:in `exists?'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/property/ensure.rb:81:in `retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1070:in `retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1098:in `retrieve_resource'`

## Any additional information you'd like to impart

The issue seems to be at the file `lib/puppet/provider/zabbix.rb` on the line 93, the function check_template_in_host() is only expecting the parameter _host_, but it should also accept the parameter _template_.

Making that change this works as expected.

If you want, I can provide a PR with this simple fix.

### PR DESCRIPTION
**Pull request by fgallese**
This simple commit fixes #594

### CODE REVIEW

**Comment by bastelfreak** [comment]
thanks for the fix!

**Comment by alexjfisher** [comment]
For the changelog, could we have a more descriptive PR title?

**Comment by alexjfisher** [comment]
Was this always broken or a recent regression?
Ping @baurmatt :)

**Comment by alexjfisher** [comment]
Small bug in 
https://github.com/voxpupuli/puppet-zabbix/pull/591

**Comment by fgallese** [comment]
> For the changelog, could we have a more descriptive PR title?

Done, sorry for that.

**Pull request merged**
