### PR TITLE
Support SSL parameters for web monitoring in all versions >= 2.4

### PR DESCRIPTION
**Pull request by anotherfigo**
This PR is for the following issue: https://github.com/voxpupuli/puppet-zabbix/issues/468

I am sorry if the tests aren't correct and will gladly improve if pointed in the right direction.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @anotherfigo, thanks for the PR. Can you check the used email address in your commits?  It isn't associated with your github account.

**Comment by anotherfigo** [comment]
@bastelfreak I'm sorry, forgot to change that in git settings...
I now associated this one to my account too.
Are the test okay?

**Comment by anotherfigo** [comment]
Do I need to provide anything else in order to this request being merged?

**Comment by bastelfreak** [comment]
Hi @anotherfigo, thanks for reminding me about this PR!

**Pull request merged**
