### PR TITLE
Add switch to disable privatetmp in the server systemd file.

### PR DESCRIPTION
**Pull request by ranzbak**
#### Pull Request (PR) description
This pool request adds a switch to the server class, to enable/disable the privatetmp option in the zabbix-server systemd file.

#### This Pull Request (PR) fixes the following issues

PrivateTmp always enabled, this messes with SNMP trap configurations #521

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @ranzbak, thanks for the PR. I'm wondering if this is the right solution to the problem. This means the shared directory will be /tmp? I don't think that this is a good idea. Wouldn't it make more sense to create a new directory which is shared between both processes exclusively?

**Comment by bastelfreak** [comment]
Please rebase after https://github.com/voxpupuli/puppet-zabbix/pull/524 got merged. That will fix the failing beaker jobs

**Comment by ranzbak** [comment]
What also could be a solution is to add : JoinsNamespaceOf=
To the systemd file so both the feeder and Zabbix share the same tmp directory.
But this doesn't make debugging the setup easy, at least for debugging the private tmp should be configurable.

**Comment by ranzbak** [comment]
Also rebase done :-)

**Comment by bastelfreak** [comment]
@ranzbak the rebase doesn't look, can you give it another shot? If you need any help with git, feel free to join our slack channel at https://slack.puppet.com or our IRC channel #voxpupuli on freenode.

**Comment by Fabian1976** [comment]
I also ran in to this issue. I fixed it by letting snmptt write the file in this location:
```/var/log/zabbix/zabbix_traps.tmp```
And setting the trapper file of the server process to the same location.

**Comment by bastelfreak** [comment]
@Fabian1976 are you interested in finishing this PR?

**Comment by Fabian1976** [comment]
@bastelfreak No, not really :)  I agree with you that this isn't the right solution to "fix" it. Just write the trapper file to another folder (not /tmp) where it can also be managed by logrotate and archived if you want to have an archive.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this PR. Please reopen it if you still think this is a good idea and we can discuss it here or on slack http://slack.puppet.com/ or our IRC channel #voxpupuli on freenode.

**Pull request closed without merging**
