### PR TITLE
updated template

### PR DESCRIPTION
**Pull request by ericsysmin**

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @ericsysmin 

Is this PR ready to be merged? Or do you have some other changed rolled up on your sleeves ;-)

**Comment by ericsysmin** [comment]
@dj-wasabi I need to check a few more items before I merge in, there's some stuff I found that may not be in the other templates.

**Comment by bastelfreak** [comment]
Hi @ericsysmin,

How is the state of the PR? Why did you downgrade the default zabbix version?

**Comment by jyaworski** [comment]
@bastelfreak we should consider turning on auto-squash for these kinds of PRs.

**Comment by bastelfreak** [comment]
squashing this one is fine. But I want to understand the reason for the downgrade of zabbix first.

**Comment by ericsysmin** [comment]
When you upgrade it caused some problems. Hence why I wanted to change it back. But at this point it's probably best to close.

**Pull request closed without merging**
