### PR TITLE
Make module run with ubuntu.

### PR DESCRIPTION
**Pull request by ITler**
This belongs to #222 and should make module run with ubuntu. I'd like to request you to extend your specs.

### CODE REVIEW

**Comment by bastelfreak** [comment]
thanks for the fix! :+1: 
Could you also add a spec test for these two resources?

**Comment by ITler** [comment]
Obviously, I'm not sure how to do this in an effective way... Also, I'm sitting in a project having time pressure. I just can't familiarize myself with adepting the specs at the moment.

**Comment by ITler** [comment]
Can we leave ticket #222 open until specs are upgraded, but already merge this PR to master?

**Comment by bastelfreak** [comment]
I will do the spec tests

**Pull request merged**
