### PR TITLE
Allow for empty MySQL password

### PR DESCRIPTION
**Pull request by JamieCressey**

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @JamieCressey 

Thank you for making time to create an PR. 
I can only accept PR that successfully exits the CI tests.

If you would please take a look at it, then I can accept it.

Kind regards,
Werner

**Comment by JamieCressey** [comment]
Oops. I'll take a look at what went wrong ASAP

**Comment by dj-wasabi** [comment]
Hi @JamieCressey

Thank you for making time to create an PR. 
I can only accept PR that successfully exits the CI tests.

If you would please take a look at it, then I can accept it.

Kind regards,
Werner

**Comment by bastelfreak** [comment]
Hi @JamieCressey,

could you please take a look and rebase?

**Comment by bastelfreak** [comment]
Hi @JamieCressey, I am going to close this PR. Please let me know if you are still interested in this.

**Pull request closed without merging**
