### PR TITLE
install Zabbix 6.0 by default everywhere but EL7

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by zilchms — APPROVED** [review]

**Review by ekohl — APPROVED** [review]

**Review by bastelfreak — APPROVED** [review]

**Comment by evgeni** [comment]
And now someone please explain to me why this breaks idempotency tests…

**Comment by evgeni** [comment]
But 6.0 should have already been tested there as we test all supported versions on all supported OSes 🤔

**Comment by evgeni** [comment]
Hah. So some testing in #893 reveals that it's also not idempotent on EL9 and more so `spec/acceptance/server_spec.rb` never tested non-default versions, and `spec/acceptance/zabbix_*_spec.rb` have some special code because the apache module (???) is not idempotent.

I'll add non-default version tests to `server_spec.rb` tomorrow and see how what the real issue is. :disappointed:

**Comment by evgeni** [comment]
```
Oct 04 16:08:23 centos8-stream.tanso.example.com systemd[1]: Started Zabbix Server.
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: Starting Zabbix Server. Zabbix 6.0.22 (revision 2b0090fc371).
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: ****** Enabled features ******
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: SNMP monitoring:           YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: IPMI monitoring:           YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: Web monitoring:            YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: VMware monitoring:         YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: SMTP authentication:       YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: ODBC:                      YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: SSH support:               YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: IPv6 support:              YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: TLS support:               YES
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: ******************************
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: using configuration file: /etc/zabbix/zabbix_server.conf
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: 
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: Unable to start Zabbix server due to unsupported PostgreSQL database version (12.12).
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: Must be at least (13.0).
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: Use of supported database version is highly recommended.
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: Override by setting AllowUnsupportedDBVersions=1 in Zabbix server configuration file at your own risk.
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: 
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: Starting Zabbix Server. Zabbix 6.0.22 (revision 2b0090fc371).
Oct 04 16:08:23 centos8-stream.tanso.example.com zabbix_server[26145]: Press Ctrl+C to exit.
Oct 04 16:08:23 centos8-stream.tanso.example.com systemd[1]: zabbix-server.service: Main process exited, code=exited, status=1/FAILURE
Oct 04 16:08:23 centos8-stream.tanso.example.com systemd[1]: zabbix-server.service: Failed with result 'exit-code'.
```

Funny that no other test caught that… "funny"…

**Comment by zilchms** [comment]
well now we know what the problem is, zabbix 6 introduces a dependency to postgres >=13. and we only tested 5.0 due to faulty spec_helper

**Comment by evgeni** [comment]
> well now we know what the problem is, zabbix 6 introduces a dependency to postgres >=13. and we only tested 5.0 due to faulty spec_helper

I don't even think it's "faulty", just that those tests weren't testing the *server* part but the API provided by `zabbix-web`, which talks directly to the DB and doesn't check the version :see_no_evil:

**Review by zilchms — APPROVED** [review]

**Pull request merged**
