### PR TITLE
Support multiple zabbix_alias

### PR DESCRIPTION
**Pull request by fribergr**
Enhancement for supporting multiple Alias-directives inside zabbix_agentd.conf.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @fribergr, thanks for this PR!
* Can you please rebase against our latest master? This should fix the acceptance tests
* Can you please add a few unit tests to verify the file content?

**Comment by fribergr** [comment]
I've added tests and rebased it against master, should be ok now.

**Comment by juniorsysadmin** [comment]
I'm uncomfortable with the abuse of Ruby internals rather than strict typing (requiring the value to be an array), but won't block the change.

**Comment by bastelfreak** [comment]
@juniorsysadmin good catch. Our next release already has a breaking change in it. So should this one here be changed to an array? Or accept string or array as a param in the module, but convert it to an array which gets passed to the template. We do that in other modules as well.

**Comment by juniorsysadmin** [comment]
@bastelfreak I would change it to an array. Less code complexity.

**Comment by bastelfreak** [comment]
@fribergr could you please change the datatype to an array?

**Comment by fribergr** [comment]
@bastelfreak I just removed string support. Does it look ok now?

**Comment by bastelfreak** [comment]
Can you add the datatype Optional[Array] to the zabbix_alias param in agent.pp?

**Comment by fribergr** [comment]
I added the requested Optional[Array], but Travis seems broken (build stuck in queued). Anything else needed?

**Comment by bastelfreak** [comment]
I restarted the job. Secret tip: You can achive the same by closing and reopening the pull request.

**Pull request merged**
