### PR TITLE
modulesync 2.7.0 and drop puppet 4

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 2.7.0

### CODE REVIEW

**Comment by dhoppe** [comment]
@bastelfreak You need to "squash and merge", because I do not know how to edit multiple files via the web interface. ;)

**Comment by dhoppe** [comment]
@bastelfreak What did you do? It looks kind of broken.

**Comment by bastelfreak** [comment]
mhm strange. Let me have a look again :D

**Comment by bastelfreak** [comment]
Replaced by https://github.com/voxpupuli/puppet-zabbix/pull/611

**Pull request closed without merging**
