### PR TITLE
Update Debian repository public key ID

### PR DESCRIPTION
**Pull request by sigv**
Ref: #461.

### CODE REVIEW

**Comment by bastelfreak** [comment]
We have acceptance tests for debian8, ubuntu14.04 and 16.04. Master is working with the current key, this PR works with the new key. something is wrong with our tests, or both keys work?

----

@sigv our current acceptance tests for the agent: https://github.com/voxpupuli/puppet-zabbix/blob/master/spec/acceptance/agent_spec.rb

can you paste your used call for the module? Do you use the agent class in a different way?

**Comment by sigv** [comment]
This is the [Release.gpg for Zabbix v3.4 for Debian Stretch](https://repo.zabbix.com/zabbix/3.4/debian/dists/stretch/Release.gpg) from the official repository as of right now:

```
-----BEGIN PGP SIGNATURE-----

iQEzBAABCgAdFiEEoYSPU1LQIrlHHYPQCCq1a6FP5ZEFAlnnQf0ACgkQCCq1a6FP
5ZFgRQf/Rk3MoW99dF/eP6eL3yczR2s1MpMl/dGnLJQ/BAcLOwMemPGrwRS8ycwU
Ytkuw6+3B1fvYRdXxP+gc9vfq6T3kuZDRrGh5fW7ctVMrh+/8vuwQjWG+fAiU0cK
1lDsB9IQMdpRE4pTA/9YuEbkj3aOLPeCUxWLpc8AARHKut1/5yKivTOVAaOFwNur
jswnc5NnZmNZZnCXwPsbcgTQ1qUufvKmqxZ1ApwEspyNENN/kSrV4VdaD6GJwUv8
GR5C0DfQ5jhYSx32rt4/EJsc46AonOWyI3sIMyyu7gz6577/TWKiDlHNi8pkfSX/
A5eCUGQWqtxEB/HClY9k4wp/DAl3wg==
=3MMd
-----END PGP SIGNATURE-----
```

If you throw that at GPG (by using `gpg -vv` and then just pasting that key) you end up with it telling you the KeyID for the signature is 082AB56BA14FE591. Not sure how the acceptance tests are doing their key verification and how repository management works in general there, but I can tell you that this key needed to be added for me to install the right Zabbix package on a new box and the signature that you can manually look at seems to confirm that.

**Comment by sigv** [comment]
Oh, and here is how we set the module up in our Puppet configuration for completeness' sake.

---

```yaml
zabbix::agent::zabbix_version: '3.2'
zabbix::agent::server: 'foo-zabbix.example.com'
zabbix::agent::listenip: 'eth0'
zabbix::agent::unsafeuserparameters: 1
```

```pp
class profile::zabbix {
  include ::zabbix::agent
}
```

Along with some `Zabbix_userparameters` definitions later down the line.

**Comment by sigv** [comment]
Bump?

**Comment by ekohl** [comment]
I wonder if that key is even used or if it'll use the key file which contains both keys:
```
$ gpg2 Downloads/zabbix-official-repo.key 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   dsa1024 2012-10-28 [SC]
      FBABD5FB20255ECAB22EE194D13D58E479EA5ED4
uid           Zabbix SIA <packager@zabbix.com>
sub   elg1024 2012-10-28 [E]
pub   rsa2048 2016-07-15 [SC]
      A1848F5352D022B9471D83D0082AB56BA14FE591
uid           Zabbix LLC <packager@zabbix.com>
sub   rsa2048 2016-07-15 [E]
```

**Comment by sigv** [comment]
Would you propose adding both keys from the `zabbix-official-repo.key` in that case?

**Comment by sigv** [comment]
Now there will be both `/Stage[main]/Zabbix::Repo/Apt::Key[zabbix-FBABD5F]/Apt_key[zabbix-FBABD5F]/ensure` as well as `/Stage[main]/Zabbix::Repo/Apt::Key[zabbix-A1848F5]/Apt_key[zabbix-A1848F5]/ensure` which should cover all grounds. Any comments on this?

**Pull request merged**
